<a href="https://colab.research.google.com/github/sherlyxdaisy/ipec/blob/main/EXCISE2_NUMPY_work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
print(np.add)

<ufunc 'add'>


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
x = np.zeros(10)
x[4] = 1
print(x)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
x = np.arange(10, 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
x = [1, 2, 3, 4, 5]
reversed_x = x[::-1]
print(reversed_x)

[5, 4, 3, 2, 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
m = np.arange(9).reshape(3, 3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
m = np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.40573387 0.80996396 0.707674  ]
  [0.1155967  0.07764693 0.83536993]
  [0.0935417  0.92687374 0.80830131]]

 [[0.77919805 0.51046251 0.62199286]
  [0.10105787 0.88091881 0.14233461]
  [0.24252244 0.50301167 0.04523063]]

 [[0.8805656  0.91011824 0.44043939]
  [0.8873679  0.79907205 0.33227702]
  [0.75733104 0.86635238 0.64183003]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr = np.random.random((10, 10))

print("Original Array:")
print(arr)

min_value = arr.min()
max_value = arr.max()

print("Minimum and Maximum Values:")
print(min_value, max_value)

Original Array:
[[0.31455571 0.43338779 0.52443568 0.01327896 0.91618296 0.92136299
  0.63875693 0.62964403 0.23652057 0.87578531]
 [0.12721322 0.27150273 0.28571376 0.95797609 0.12422147 0.11695424
  0.88463711 0.65443854 0.62236852 0.10507477]
 [0.89592656 0.13557635 0.57221505 0.12381603 0.48024276 0.92558851
  0.35197511 0.1331181  0.59769673 0.28079776]
 [0.00525653 0.97834393 0.31017863 0.23610931 0.86613675 0.68196989
  0.24787441 0.8233061  0.04913789 0.44552739]
 [0.14409972 0.69422656 0.81974601 0.99710729 0.2223154  0.57307938
  0.37372824 0.62266287 0.63309091 0.77480855]
 [0.95354893 0.67821246 0.22521605 0.09026993 0.48320591 0.2404475
  0.61475425 0.45200987 0.13953194 0.47114881]
 [0.10398713 0.70649707 0.81848679 0.90932198 0.4543921  0.61247106
  0.92563649 0.32203153 0.95994459 0.71855825]
 [0.21973546 0.42372367 0.50741991 0.40386527 0.40792024 0.89785596
  0.87345836 0.8514329  0.98390362 0.03550674]
 [0.46377831 0.86940283 0.73237487 0.55913848 0.73761187 0.318452

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
v = np.random.random(30)
print(v)

mean = np.mean(v)
print(mean)

[0.75416832 0.44904084 0.66135936 0.70246213 0.89452052 0.49818822
 0.95080132 0.31851702 0.16516957 0.2520614  0.13895635 0.98643011
 0.98388112 0.68349973 0.88119598 0.39343286 0.18169046 0.35308181
 0.61748776 0.19453283 0.58004821 0.05096252 0.84722432 0.12775559
 0.54093157 0.19264869 0.68006128 0.36234885 0.83047824 0.29679812]
0.5189911692531389


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
def create_2d_array(n: int, m: int) -> np.ndarray:
    arr = np.ones((n, m))
    arr[1:-1, 1:-1] = 0
    return arr

n, m = 5, 7
arr = create_2d_array(n, m)
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
def add_border(arr: np.ndarray) -> np.ndarray:
    n, m = arr.shape
    new_arr = np.zeros((n + 2, m + 2))
    new_arr[1:-1, 1:-1] = arr
    return new_arr

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
bordered_arr = add_border(arr)
print(bordered_arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 4. 5. 6. 0.]
 [0. 7. 8. 9. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan # evaluates to nan
np.nan == np.nan # evaluates to False
np.inf > np.nan # evaluates to False
np.nan - np.nan # evaluates to nan
np.nan in set([np.nan]) # evaluates to True
0.3 == 3 * 0.1 # evaluates to False


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
def create_matrix(n: int) -> np.ndarray:
    arr = np.zeros((n, n))
    np.fill_diagonal(arr[1:], [1, 2, 3, 4])
    return arr

n = 5
matrix = create_matrix(n)
print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
def create_checkerboard(n: int) -> np.ndarray:
    arr = np.zeros((n, n), dtype=int)
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr

n = 8
checkerboard = create_checkerboard(n)
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
shape = (6, 7, 8)
index_100 = 99
x, y, z = np.unravel_index(index_100, shape)
print(f"The index (x, y, z) of the 100th element is ({x}, {y}, {z})")

The index (x, y, z) of the 100th element is (1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
def create_checkerboard(n: int) -> np.ndarray:
    tile = np.array([[0, 1], [1, 0]])
    arr = np.tile(tile, (n // 2, n // 2))
    if n % 2 != 0:
        arr = np.pad(arr, ((0, 1), (0, 1)), constant_values=0)
    return arr

n = 8
checkerboard = create_checkerboard(n)
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
matrix = np.random.random((5, 5))
matrix_normalized = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))

print(matrix_normalized)

[[0.33330839 0.3456181  0.57921976 0.         0.93681972]
 [0.8153545  0.49092007 0.57134011 1.         0.35371131]
 [0.15915913 0.64834881 0.13144426 0.24145342 0.37448423]
 [0.14807575 0.66081998 0.01792411 0.92237302 0.57001935]
 [0.57495302 0.19414816 0.36729061 0.93110731 0.8354706 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color_dtype = np.dtype([
    ("r", np.uint8),
    ("g", np.uint8),
    ("b", np.uint8),
    ("a", np.uint8)])
color = np.array((255, 0, 0, 255), dtype=color_dtype)
print(color)

(255, 0, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((3, 2))

product = np.matmul(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)
print("Product:")
print(product)

Matrix 1:
[[0.93570195 0.6907089  0.84303072]
 [0.43618706 0.81983353 0.32294644]
 [0.54676502 0.02458206 0.76887801]
 [0.25904992 0.51841006 0.14828692]
 [0.02180745 0.46178327 0.49031703]]
Matrix 2:
[[0.94215494 0.31327531]
 [0.95645918 0.15117122]
 [0.02850477 0.0193756 ]]
Product:
[[1.56624147 0.41388185]
 [1.20429861 0.26683915]
 [0.56056579 0.18990155]
 [0.74413011 0.16239577]
 [0.47619921 0.08614026]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
def negate_elements(arr):
    for i in range(len(arr)):
        if 3 < arr[i] < 8:
            arr[i] = -arr[i]
    return arr
arr = [1, 4, 6, 8, 10]
result = negate_elements(arr)
print(result)

[1, -4, -6, 8, 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(3)

Z ** Z  # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2  # = [0, 1, 2]
Z < -Z  # = [False, False, False]
1j * Z  # = [0.+0.j, 0.+1.j, 0.+2.j]
Z / 1 / 1  # = [0, 1, 2]

array([0., 1., 2.])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-27-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-27-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
def round_away_from_zero(arr):
    return np.fix(arr)

arr = np.array([-2.9, -1.5, 0.7, 1.3, 2.8])
result = round_away_from_zero(arr)
print(result)

[-2. -1.  0.  1.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(arr1, arr2)

print(common_values)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import warnings
warnings.filterwarnings("ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
# Given arrays A and B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Compute the expression in place
np.multiply(np.add(A, B), np.divide(-A, 2), out=A)

print("Resulting array A:")
print(A)

UFuncTypeError: ignored

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [ ]:
# Method 1: Using the np.fix function
arr = np.random.random(5) * 10
integer_part = np.fix(arr)
print(integer_part)

# Method 2: Using the np.floor function
arr = np.random.random(5) * 10
integer_part = np.floor(arr)
print(integer_part)

# Method 3: Using the np.trunc function
arr = np.random.random(5) * 10
integer_part = np.trunc(arr)
print(integer_part)

# Method 4: Using the astype method
arr = np.random.random(5) * 10
integer_part = arr.astype(int)
print(integer_part)

# Method 5: Using the np.ceil and np.where functions
arr = np.random.random(5) * 10
integer_part = np.where(arr < 0, np.ceil(arr), np.floor(arr))
print(integer_part)

[7. 8. 5. 3. 5.]
[6. 0. 4. 1. 4.]
[3. 3. 4. 4. 3.]
[9 9 0 6 6]
[0. 8. 5. 0. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix = np.zeros((5, 5))
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate_integers():
    for i in range(10):
        yield i
arr = np.fromiter(generate_integers(), dtype=int)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
vector = np.linspace(0, 1, num=12, endpoint=True)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
vector = np.random.random(10)
vector.sort()
print(vector)

[0.02273054 0.28588072 0.35389347 0.407816   0.5397193  0.59803941
 0.65235985 0.69383233 0.81804713 0.98755805]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
result = sum(arr)
print(result)

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.random(5)
B = np.random.random(5)
are_equal = np.array_equal(A, B)
print(are_equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr = np.array([1, 2, 3])
arr.flags.writeable = False

print(arr)

[1 2 3]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
# Generate a random 10x2 matrix representing Cartesian coordinates
cartesian_coordinates = np.random.random((10, 2))

# Convert Cartesian coordinates to polar coordinates
radii = np.linalg.norm(cartesian_coordinates, axis=1)
angles = np.arctan2(cartesian_coordinates[:, 1], cartesian_coordinates[:, 0])

# Combine radii and angles into a polar coordinates matrix
polar_coordinates = np.column_stack((radii, angles))

print(polar_coordinates)

[[0.67122465 1.05075283]
 [0.96880492 0.60349203]
 [0.8721651  0.87374206]
 [1.21847911 0.88775108]
 [0.48427264 1.32318576]
 [0.39293236 1.26246139]
 [0.96602137 0.14921685]
 [0.86810884 1.0381925 ]
 [0.95931756 0.93003635]
 [0.62335883 0.55955517]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
# Create a random vector of size 10
vector = np.random.random(10)

# Replace the maximum value with 0
vector[vector.argmax()] = 0

print("Original vector:")
print(vector)

Original vector:
[0.35835899 0.33430778 0.68610314 0.83850356 0.10331595 0.0603295
 0.         0.16525397 0.69608437 0.50098656]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
# Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
x, y = np.meshgrid(np.linspace(0, 1, num=10), np.linspace(0, 1, num=10))
structured_array = np.zeros((10, 10), dtype=[('x', float), ('y', float)])
structured_array['x'], structured_array['y'] = x.flatten(), y.flatten()

print("Structured array with x and y coordinates covering the [0,1]x[0,1] area:")
print(structured_array)

ValueError: ignored

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
# Given arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix C
C = 1 / (X[:, np.newaxis] - Y)

print("Cauchy matrix C:")
print(C)

Cauchy matrix C:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
import numpy as np

# Integer types
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    print(f"{dtype.__name__}: The minimum value is {np.iinfo(dtype).min} and the maximum value is {np.iinfo(dtype).max}.")

# Unsigned integer types
for dtype in [np.uint8, np.uint16, np.uint32, np.uint64]:
    print(f"{dtype.__name__}: The minimum value is {np.iinfo(dtype).min} and the maximum value is {np.iinfo(dtype).max}.")

# Floating-point types
for dtype in [np.float16, np.float32, np.float64]:
    print(f"{dtype.__name__}: The minimum positive normalized value is approximately {np.finfo(dtype).tiny} and the maximum positive normalized value is approximately {np.finfo(dtype).max}.")


int8: The minimum value is -128 and the maximum value is 127.
int16: The minimum value is -32768 and the maximum value is 32767.
int32: The minimum value is -2147483648 and the maximum value is 2147483647.
int64: The minimum value is -9223372036854775808 and the maximum value is 9223372036854775807.
uint8: The minimum value is 0 and the maximum value is 255.
uint16: The minimum value is 0 and the maximum value is 65535.
uint32: The minimum value is 0 and the maximum value is 4294967295.
uint64: The minimum value is 0 and the maximum value is 18446744073709551615.
float16: The minimum positive normalized value is approximately 6.103515625e-05 and the maximum positive normalized value is approximately 65504.0.
float32: The minimum positive normalized value is approximately 1.1754943508222875e-38 and the maximum positive normalized value is approximately 3.4028234663852886e+38.
float64: The minimum positive normalized value is approximately 2.2250738585072014e-308 and the maximum positive

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
# Create an array
array = np.array([1, 2, 3, 4, 5])

# Set print options to display all values
np.set_printoptions(threshold=np.inf)

# Print the array
print(array)

[1 2 3 4 5]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
# Given vector and scalar
vector = np.array([1, 2, 3, 4, 5])
scalar = 2.5

# Find the index of the closest value
index = np.abs(vector - scalar).argmin()

# Get the closest value
closest_value = vector[index]

print("Closest value:", closest_value)

Closest value: 2


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
# Create a structured array with position (x,y) and color (r,g,b)
structured_array = np.zeros(10, dtype=[('position', [('x', float), ('y', float)]), ('color', [('r', float), ('g', float), ('b', float)])])

# Generate random values for position and color
structured_array['position']['x'] = np.random.random(10) * 10
structured_array['position']['y'] = np.random.random(10) * 10
structured_array['color']['r'] = np.random.random(10) * 255
structured_array['color']['g'] = np.random.random(10) * 255
structured_array['color']['b'] = np.random.random(10) * 255

print("Structured array representing a position (x,y) and a color (r,g,b):")
print(structured_array)

Structured array representing a position (x,y) and a color (r,g,b):
[((9.63174369, 9.21472148), (236.07945418,  40.50297803,  61.12272426))
 ((7.15670909, 4.92927078), (192.0608549 , 166.84973262, 186.49108878))
 ((1.45686459, 2.65205275), ( 43.53729982, 168.32039014,   4.06385946))
 ((5.4791382 , 8.8456853 ), (217.47213785, 108.44964229, 219.8932947 ))
 ((9.27956684, 3.31379566), (198.96194455, 222.3992924 , 116.02603313))
 ((7.60815222, 4.05014187), ( 98.8341852 ,  41.62388143, 166.76634548))
 ((9.82384963, 5.87747798), (162.36355217,  19.32734714, 109.00538365))
 ((2.51523809, 4.61166066), (110.5006465 , 172.05670718,  95.85621454))
 ((0.39930975, 4.09244887), (161.02417374,  79.37191123,  31.32241466))
 ((4.49405524, 2.38721846), (160.22837312,  21.24412894, 235.98150511))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
# Given vector with shape (100,2)
vector = np.random.random((100, 2))

# Calculate point by point distances
distances = np.sqrt(np.sum(np.square(vector[:, np.newaxis] - vector), axis=2))

print("Point by point distances:")
print(distances)

Point by point distances:
[[0.00000000e+00 1.23731008e-01 1.66956890e-01 3.04667115e-01
  4.13583434e-01 5.31352434e-01 1.67503926e-01 1.55695802e-01
  3.11862445e-01 3.20806504e-01 2.77094517e-01 9.52577067e-02
  5.14098043e-01 5.53777159e-01 2.27638647e-01 2.07345880e-01
  5.92191733e-01 4.98341944e-01 4.85990192e-02 7.15980219e-01
  3.55913765e-01 4.12921759e-01 2.42315813e-01 1.40915016e-01
  2.87651728e-01 4.57181605e-01 3.86222167e-01 6.73502950e-01
  2.86831721e-01 5.06619974e-01 5.30000430e-01 4.97966998e-01
  4.78278601e-01 3.02203629e-01 4.91668497e-01 3.87388274e-01
  6.35945864e-01 4.19796930e-01 5.37785822e-01 4.58204113e-01
  6.05399353e-01 5.91998055e-01 4.95174047e-01 4.03572875e-01
  5.74064167e-01 5.02518160e-01 4.28210985e-01 2.34981785e-01
  4.15565738e-01 1.75634459e-01 3.73991265e-01 2.99676244e-01
  4.74997770e-01 5.25824026e-01 3.70557204e-01 3.46366794e-01
  5.54323102e-01 2.56926778e-01 3.84421261e-01 3.61538658e-01
  3.97554510e-01 3.45336779e-01 5.14988744e-

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
# Create a float array
float_array = np.array([1.5, 2.7, 3.9], dtype=np.float32)

# Convert the float array to an integer array in place
float_array = float_array.astype(np.int32)

print("Integer array:")
print(float_array)

Integer array:
[1 2 3]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
with open('filename.txt', 'r') as file:
    for line in file:
        values = line.strip().split(',')
        print(values)

FileNotFoundError: ignored

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
# Create a Numpy array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Iterate over the array with ndenumerate
for index, value in np.ndenumerate(array):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
# Create a meshgrid of x and y coordinates
x, y = np.meshgrid(np.linspace(-1, 1, num=10), np.linspace(-1, 1, num=10))

# Calculate the distance from the origin
d = np.sqrt(x**2 + y**2)

# Set the parameters for the Gaussian-like array
sigma, mu = 1.0, 0.0

# Calculate the Gaussian-like array
g = np.exp(-((d - mu)**2 / (2.0 * sigma**2)))

print("2D Gaussian-like array:")
print(g)

2D Gaussian-like array:
[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
# Define the size of the 2D array
m, n = 5, 5

# Define the number of elements to place randomly
p = 3

# Create a zeros-initialized 2D array
array = np.zeros((m, n), dtype=bool)

# Generate random indices and set the corresponding elements to True
indices = np.random.choice(m * n, p, replace=False)
array.flat[indices] = True

print("Randomly placed elements in the 2D array:")
print(array)

Randomly placed elements in the 2D array:
[[False False False False  True]
 [ True False False False False]
 [False False False False False]
 [False False False False False]
 [ True False False False False]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Subtract the mean of each row
result = matrix - np.mean(matrix, axis=1, keepdims=True)

print("Result:")
print(result)

Result:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
import numpy as np

# Create a sample array
a = np.array([[9, 2, 3], [4, 5, 6], [7, 0, 5]])

# Sort the rows of 'a' by the second column
a = a[a[:, 1].argsort()]

print(a)


[[7 0 5]
 [9 2 3]
 [4 5 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Check if any column is filled with 0
null_columns = (~array.any(axis=0)).any()

print("Null columns:", null_columns)

Null columns: False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
import numpy as np

def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

# Example usage:
array = np.random.random(10)
print(array)  # [0.21069679 0.61290182 0.63425412 0.84635244 0.91599191 0.00213826
              # 0.17104965 0.56874386 0.57319379 0.28719469]
print(find_nearest(array, value=0.5))  # 0.568743859261


[0.21561379 0.34460526 0.62879123 0.04268712 0.65638681 0.5236537
 0.18907522 0.53316402 0.26925175 0.402771  ]
0.5236537007075037


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
# Create the two arrays
A = np.array([[1, 2, 3]])
B = np.array([[4], [5], [6]])

# Create an iterator over the arrays
it = np.nditer([A, B])

# Initialize a variable to store the sum
sum = 0

# Iterate over the arrays and compute the sum
for x, y in it:
    sum += x + y

print("Sum:", sum)

Sum: 63


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

# Create an instance of the NamedArray class with a name attribute
my_array = NamedArray([1, 2, 3], name="my_array")

# Access the name attribute
print(my_array.name)

my_array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
# Create the first vector
vector1 = np.array([1, 2, 3, 4, 5])

# Create the second vector with indices
indices = np.array([0, 1, 2, 2, 3])

# Add 1 to each element of the first vector indexed by the second vector
vector1[indices] += 1

print("Resulting vector:")
print(vector1)

Resulting vector:
[2 3 4 5 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
# Create the vector X
X = np.array([1, 2, 3, 4, 5])

# Create the array F
F = np.zeros(10)

# Create the index list I
I = np.array([0, 1, 2, 2, 3])

# Accumulate elements of X to F based on I
np.add.at(F, I, X)

print("Resulting array F:")
print(F)

Resulting array F:
[1. 2. 7. 5. 0. 0. 0. 0. 0. 0.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [ ]:
import numpy as np

def count_unique_colors(image):
    unique_colors = np.unique(image.reshape(-1, 3), axis=0)
    return len(unique_colors)

# Example usage:
image = np.random.randint(0, 256, size=(100, 100, 3), dtype=np.uint8)
print(count_unique_colors(image))


9998


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
# Create a four-dimensional array
array = np.random.random((2, 3, 4, 5))

# Get the sum over the last two axes
result = np.sum(array, axis=(-2, -1))

print("Resulting array:")
print(result)

Resulting array:
[[10.71188321 10.00911753 12.29901078]
 [12.32444892  6.92686782 10.39436591]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
# Create the one-dimensional vector D
D = np.array([1, 2, 3, 4, 5])

# Create the vector S describing subset indices
S = np.array([0, 0, 1, 1, 1])

# Compute the means of subsets of D using S
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts

print("Means of subsets of D:")
print(D_means)

Means of subsets of D:
[1.5 4. ]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
import numpy as np

def diagonal_of_dot_product(a, b):
    dot_product = np.dot(a, b)
    diagonal = np.diag(dot_product)
    return diagonal

# Example usage:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(diagonal_of_dot_product(a, b))  # [68 167 266]


[ 84 216 366]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
nums = np.array([1, 2, 3, 4, 5])
p = 3
new_nums = np.zeros(len(nums) + (len(nums) - 1) * p)
new_nums[::p + 1] = nums

print("Original array:")
print(nums)
print("\nNew array:")
print(new_nums)

Original array:
[1 2 3 4 5]

New array:
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
# Create the first array of dimension (5,5,3)
array1 = np.random.rand(5, 5, 3)

# Create the second array of dimension (5,5)
array2 = np.random.rand(5, 5)

# Multiply the two arrays
result = array1 * array2[:, :, None]

print("Original array of dimension (5,5,3):")
print(array1)
print("\nArray with dimensions (5,5):")
print(array2)
print("\nResult of multiplication:")
print(result)

Original array of dimension (5,5,3):
[[[0.19407809 0.96043972 0.78078748]
  [0.96845033 0.02710704 0.94555532]
  [0.75725419 0.80942486 0.83923207]
  [0.19309671 0.06216325 0.27838268]
  [0.35486628 0.03603637 0.64290903]]

 [[0.16791106 0.47271096 0.45104063]
  [0.98230933 0.95298009 0.95909889]
  [0.35486101 0.8568309  0.87855121]
  [0.27989416 0.01952217 0.62553326]
  [0.24136475 0.02151609 0.72132694]]

 [[0.8689288  0.50165675 0.98214925]
  [0.17746766 0.91825864 0.79864373]
  [0.55786078 0.08799613 0.94122357]
  [0.99648552 0.88401348 0.69468918]
  [0.8384461  0.55536571 0.24863309]]

 [[0.97086673 0.43968032 0.38947393]
  [0.75192309 0.80707838 0.17279713]
  [0.19373865 0.54113949 0.06683289]
  [0.93489118 0.70329556 0.27544388]
  [0.5348541  0.07769405 0.77884883]]

 [[0.98447704 0.76096816 0.15741892]
  [0.23266447 0.80189999 0.16283778]
  [0.42776178 0.66491279 0.72871822]
  [0.72054137 0.76143515 0.68323815]
  [0.65971897 0.88531817 0.16930507]]]

Array with dimensions (5,5)

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
# Create a sample array
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])
print("Original array:")
print(a)

# Swap rows 0 and 2
a[[0, 2]] = a[[2, 0]]
print("\nArray after swapping rows:")
print(a)

Original array:
[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]

Array after swapping rows:
[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
# Create a set of 10 triplets describing 10 triangles
triangles = np.random.randint(0, 100, (10, 3))

# Roll the triangles array to create line segments
segments = np.roll(triangles.repeat(2, axis=1), -1, axis=1)

# Reshape the segments array
segments = segments.reshape(len(segments) * 3, 2)

# Find the set of unique line segments
unique_segments = np.unique(segments, axis=0)

print("Set of unique line segments:")
print(unique_segments)

Set of unique line segments:
[[ 0 31]
 [ 1 98]
 [ 5  1]
 [ 9 94]
 [22  0]
 [22 53]
 [25 73]
 [26 49]
 [28 26]
 [31 22]
 [34 36]
 [36 72]
 [39 25]
 [42 85]
 [49 28]
 [53 96]
 [57 57]
 [57 83]
 [69 75]
 [72 34]
 [73 39]
 [75  9]
 [75 95]
 [83 57]
 [85 94]
 [94 42]
 [94 75]
 [95 69]
 [96 22]
 [98  5]]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n):
    test = np.cumsum(a, dtype=float)
    test[n:] = test[n:] - test[:-n]
    return test[n - 1:] / n

a = np.arange(20)
window_size = 5
moving_average(a, window_size)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
Z = np.array([1, 2, 3, 4, 5])
A = np.vstack((Z[:3], np.vstack((Z[i:i+3] for i in range(1, len(Z)-2)))))

print("Original array:")
print(Z)
print("\nTwo-dimensional array:")
print(A)

Original array:
[1 2 3 4 5]

Two-dimensional array:
[[1 2 3]
 [2 3 4]
 [3 4 5]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
# Negate a boolean array
bool_array = np.array([True, False, True])
negated_bool_array = ~bool_array
print("Negated boolean array:", negated_bool_array)

# Change the sign of a float array inplace
float_array = np.array([1.0, -2.0, 3.0])
float_array *= -1
print("Float array with changed sign:", float_array)

Negated boolean array: [False  True False]
Float array with changed sign: [-1.  2. -3.]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance_to_lines(P0, P1, p):
    d = np.abs(np.cross(P1 - P0, P0 - p)) / np.linalg.norm(P1 - P0)
    return d

P0 = np.array([[1, 2], [3, 4], [5, 6]])
P1 = np.array([[7, 8], [9, 10], [11, 12]])
p = np.array([13, 14])

distances = distance_to_lines(P0, P1, p)
print(distances)

[0. 0. 0.]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance_to_lines(P0, P1, P):
    d = np.abs(np.cross(P1[:, None] - P0[:, None], P0[:, None] - P, axis=-1)) / np.linalg.norm(P1[:, None] - P0[:, None], axis=-1)
    return d

P0 = np.array([[1, 2], [3, 4], [5, 6]])
P1 = np.array([[7, 8], [9, 10], [11, 12]])
P = np.array([[13, 14], [15, 16]])

distances = distance_to_lines(P0, P1, P)
print(distances)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
def extract_subpart(array, shape, center, fill_value=0):
    subpart = np.full(shape, fill_value)
    indices = np.clip(center - np.array(shape) // 2, 0, np.subtract(array.shape, shape))
    slices = tuple(slice(start, start + size) for start, size in zip(indices, shape))
    subpart_indices = tuple(slice(0, size) for size in shape)
    subpart[subpart_indices] = array[slices]
    return subpart

array = np.arange(25).reshape((5, 5))
shape = (3, 3)
center = (2, 2)
subpart = extract_subpart(array, shape, center)

print("Original array:")
print(array)
print("\nExtracted subpart:")
print(subpart)

Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Extracted subpart:
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
R = np.lib.stride_tricks.as_strided(Z, shape=(11, 4), strides=(Z.itemsize, Z.itemsize))

print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
# Create a sample matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the rank
rank = np.linalg.matrix_rank(matrix)

print("Matrix Rank:", rank)

Matrix Rank: 2


#### 83. How to find the most frequent value in an array?

In [ ]:
# Create a NumPy array
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

print("Original array:")
print(x)

print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
# Create a random 10x10 matrix
matrix = np.random.randint(0, 10, (10, 10))

# Extract all the contiguous 3x3 blocks
blocks = np.lib.stride_tricks.as_strided(matrix, shape=(8, 8, 3, 3), strides=matrix.strides * 2)

print("Contiguous 3x3 blocks:")
for block in blocks:
    print(block)

Contiguous 3x3 blocks:
[[[5 9 4]
  [3 6 5]
  [7 7 2]]

 [[9 4 2]
  [6 5 6]
  [7 2 8]]

 [[4 2 1]
  [5 6 5]
  [2 8 4]]

 [[2 1 8]
  [6 5 3]
  [8 4 6]]

 [[1 8 9]
  [5 3 8]
  [4 6 5]]

 [[8 9 4]
  [3 8 9]
  [6 5 8]]

 [[9 4 7]
  [8 9 3]
  [5 8 4]]

 [[4 7 1]
  [9 3 6]
  [8 4 8]]]
[[[3 6 5]
  [7 7 2]
  [6 5 8]]

 [[6 5 6]
  [7 2 8]
  [5 8 1]]

 [[5 6 5]
  [2 8 4]
  [8 1 4]]

 [[6 5 3]
  [8 4 6]
  [1 4 0]]

 [[5 3 8]
  [4 6 5]
  [4 0 1]]

 [[3 8 9]
  [6 5 8]
  [0 1 8]]

 [[8 9 3]
  [5 8 4]
  [1 8 4]]

 [[9 3 6]
  [8 4 8]
  [8 4 4]]]
[[[7 7 2]
  [6 5 8]
  [5 2 1]]

 [[7 2 8]
  [5 8 1]
  [2 1 7]]

 [[2 8 4]
  [8 1 4]
  [1 7 3]]

 [[8 4 6]
  [1 4 0]
  [7 3 8]]

 [[4 6 5]
  [4 0 1]
  [3 8 8]]

 [[6 5 8]
  [0 1 8]
  [8 8 9]]

 [[5 8 4]
  [1 8 4]
  [8 9 0]]

 [[8 4 8]
  [8 4 4]
  [9 0 7]]]
[[[6 5 8]
  [5 2 1]
  [3 4 5]]

 [[5 8 1]
  [2 1 7]
  [4 5 3]]

 [[8 1 4]
  [1 7 3]
  [5 3 3]]

 [[1 4 0]
  [7 3 8]
  [3 3 4]]

 [[4 0 1]
  [3 8 8]
  [3 4 5]]

 [[0 1 8]
  [8 8 9]
  [4 5 1]]

 [[1 8 4]
  [8 9 

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)

# Create a symmetric 2D array
Z = np.zeros((3, 3))
Z = Z.view(SymmetricArray)

# Set values
Z[0, 1] = 1
Z[1, 2] = 2

print(Z)

[[0. 1. 0.]
 [1. 0. 2.]
 [0. 2. 0.]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
import numpy as np

def sum_of_matrix_products(matrices, vectors):
    result = np.sum([np.dot(matrix, vector) for matrix, vector in zip(matrices, vectors)], axis=0)
    return result

# Example usage:
p = 3  # Number of matrices and vectors
n = 4  # Shape of matrices and vectors
matrices = [np.random.random((n, n)) for _ in range(p)]
vectors = [np.random.random((n, 1)) for _ in range(p)]
result = sum_of_matrix_products(matrices, vectors)
print(result)


[[1.84916842]
 [1.98723997]
 [2.4399381 ]
 [2.75629434]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
# Create a 16x16 array
array = np.random.randint(0, 10, (16, 16))

# Reshape the array to split it into blocks of size 4x4
blocks = np.lib.stride_tricks.as_strided(array, shape=(4, 4, 4, 4), strides=array.strides * 2)

# Compute the sum of each block
block_sums = blocks.sum(axis=(2, 3))

print(block_sums)

[[70 67 74 74]
 [71 57 63 70]
 [76 63 65 66]
 [77 71 81 73]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# Define the size of the board
n = 100

# Create a random initial configuration
board = np.random.randint(2, size=(n, n))

# Define a function to update the board at each time step
def update_board(frame):
    # Compute the number of neighbors for each cell
    neighbors = (
        np.roll(board, 1, axis=0)
        + np.roll(board, -1, axis=0)
        + np.roll(board, 1, axis=1)
        + np.roll(board, -1, axis=1)
        + np.roll(np.roll(board, 1, axis=0), 1, axis=1)
        + np.roll(np.roll(board, -1, axis=0), -1, axis=1)
        + np.roll(np.roll(board, 1, axis=0), -1, axis=1)
        + np.roll(np.roll(board, -1, axis=0), 1, axis=1)
    )

    # Update the state of each cell based on its neighbors
    board[(board == 1) & ((neighbors < 2) | (neighbors > 3))] = 0
    board[(board == 0) & (neighbors == 3)] = 1

    # Update the plot with the new board state
    plt.imshow(board)

# Create an animation of the Game of Life
fig = plt.figure()
ani = animation.FuncAnimation(fig, update_board)

plt.show()

<Figure size 640x480 with 0 Axes>

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
# Create a NumPy array
arr = np.array([9, 4, 7, 1, 3, 6, 8, 2, 5])

# Get the n largest values
n = 3
largest_values = np.partition(arr, -n)[-n:]

print(largest_values)

[7 8 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
# Approach 1: itertools.product() method
import itertools as it
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([1, 2, 3])

output = np.array(list(it.product(array1, array2)))
print(output)

# Approach 2: Utilize the meshgrid() method from the NumPy library
array1 = np.array([1, 2, 3])
array2 = np.array([1, 2, 3])

X, Y = np.meshgrid(array1, array2)
output = np.column_stack((X.ravel(), Y.ravel()))
print(output)

#Approach 3: Combination of numpy.transpose(), numpy.tile(), and numpy.repeat()
array1 = np.array([1, 2, 3])
array2 = np.array([1, 2, 3])

cross_product = np.transpose([np.tile(array1, len(array2)), np.repeat(array2, len(array1))])
print(cross_product)

[[1 1]
 [1 2]
 [1 3]
 [2 1]
 [2 2]
 [2 3]
 [3 1]
 [3 2]
 [3 3]]
[[1 1]
 [2 1]
 [3 1]
 [1 2]
 [2 2]
 [3 2]
 [1 3]
 [2 3]
 [3 3]]
[[1 1]
 [2 1]
 [3 1]
 [1 2]
 [2 2]
 [3 2]
 [1 3]
 [2 3]
 [3 3]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
# Create a regular array
regular_array = np.array([[5, 10, 15], [20, 25, 30]])

# Create a record array from the regular array
record_array = np.core.records.fromarrays(regular_array.T, dtype=[('field1', int), ('field2', int), ('field3', int)])

print("Record Array:")
print(record_array)

Record Array:
[( 5, 10, 15) (20, 25, 30)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
import numpy as np

Z_cubed = np.power(Z, 3)


TypeError: ignored

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

rows = np.where(np.all(np.isin(A[:, :, np.newaxis], B), axis=1))[0]
print(rows)


[3]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
matrix = np.random.randint(0, 5, (10, 3))
unequal_rows = matrix[~np.logical_and.reduce(matrix[:, 1:] == matrix[:, :-1], axis=1)]
print(unequal_rows)

[[4 3 4]
 [2 2 3]
 [3 1 1]
 [3 3 1]
 [0 1 3]
 [4 1 1]
 [1 3 4]
 [3 3 4]
 [4 0 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9]])

# Extract unique rows
unique_rows = np.unique(array, axis=0)

print("Unique Rows:")
print(unique_rows)

Unique Rows:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)
np.einsum('i->', A)
np.einsum('i,i->i', A, B)

ValueError: ignored

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
X = np.array([1, 2, 3, ..., n])  # Replace '...' with the remaining elements of the vector
Y = np.array([1, 2, 3, ..., n])  # Replace '...' with the remaining elements of the vector

# Compute the length of the path
path_length = np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
path_length = np.insert(path_length, 0, 0)  # Add the starting point

# Compute the number of samples
num_samples = 100

# Compute the sample points
sample_points = np.linspace(0, path_length[-1], num_samples)

# Interpolate X and Y at the sample points
sampled_X = np.interp(sample_points, path_length, X)
sampled_Y = np.interp(sample_points, path_length, Y)

# Print the sampled points
print("Sampled Points:")
print(np.column_stack((sampled_X, sampled_Y)))

TypeError: ignored

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
n = 10
X = np.array([[1, 2, 3], [4, 5, 1], [0, 0, 10], [5, 5, 0]])

# Select rows that contain integers and sum to n
selected_rows = X[(X.sum(axis=1) == n) & (X % 1 == 0)]

print("Selected Rows:")
print(selected_rows)

ValueError: ignored

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.array([1, 2, 3, ..., n])  # Replace '...' with the remaining elements of the array

# Number of bootstrap samples
N = 1000

# Resample the elements of X with replacement N times
bootstrap_samples = np.random.choice(X, size=(N, len(X)), replace=True)

# Compute the mean of each bootstrap sample
bootstrap_means = np.mean(bootstrap_samples, axis=1)

# Compute the percentiles over the means
lower_percentile = np.percentile(bootstrap_means, 2.5)
upper_percentile = np.percentile(bootstrap_means, 97.5)

# Print the confidence interval
print("Bootstrapped 95% Confidence Interval:")
print(f"({lower_percentile}, {upper_percentile})")

TypeError: ignored